package com.massfords.maven.spel;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.maven.plugin.MojoExecutionException;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * @author slazarus
 */
public class SpelValidationReport {

    private int checked = 0;

    private int valid = 0;

    private int invalid = 0;

    private final List<String> errors = new ArrayList<String>();

    protected SpelValidationReport error(String error) {
        this.errors.add(error);
        ++this.invalid;
        ++this.checked;
        return this;
    }

    protected SpelValidationReport success() {
        ++this.valid;
        ++this.checked;
        return this;
    }


    @javax.annotation.Generated("generated by IDE")
    public List<String> getErrors() {
        return errors;
    }


    protected void createReportFile(File file) throws MojoExecutionException {
        ObjectMapper mapper = new ObjectMapper();
        try {
            mapper.writeValue(file, this);
        } catch (Exception e) {
            throw new MojoExecutionException("Failed to create a report file.", e);
        }
    }

}
