package com.massfords.maven.spel;

import javax.annotation.Generated;

/**
 * @author markford
 */
public class SpelAnnotation {
    private String name;
    private String attribute = "value";

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public SpelAnnotation setName(String name) {
        this.name = name;
        return this;
    }

    @Generated("generated by IDE")
    public String getAttribute() {
        return attribute;
    }

    @Generated("generated by IDE")
    public SpelAnnotation setAttribute(String attribute) {
        this.attribute = attribute;
        return this;
    }
}
